### PR TITLE
Refine regions

### PR DESCRIPTION
**Pull request by mundya**
From discussions with @mossblaser 
Simplifies the design of the regions utilities.

### CODE REVIEW

**Comment by mossblaser** [comment]
New API etc: looks great to me!

On to the pedantry: Despite comments and some implementation effort implying generality the Keyspace region only really supports keyspaces between 1-16, 24-32 bit keys (inclusive) due to use of struct for packing. SpiNNaker itself, of course, only "really" supports 32-bit keys. Personal preference would be to wap an assert to check keyspaces are <= 32 bits and always use a whole word per entry.

**Comment by mundya** [comment]
Yeah, that sounds sensible.

**Comment by mundya** [comment]
How about just asserting ==32?  That seems no less useful than <= 32.

**Comment by mossblaser** [comment]
Agreed :)

**Comment by mundya** [comment]
Done.

**Pull request merged**
